### ISSUE TITLE
merit_dem and merit_hydro have different usernames + passwords

### ISSUE THREAD

**Issue by jsta** [jonschwenk/rabpro#42]
The `get_merit_dem` script assumes they are identical.

**Comment by tzussman** [comment]
Will have separate download calls for the two in the CLI/data download API, so this will be fixed

**Comment by jonschwenk** [comment]
There's no need to provide downloadability for merit_dem--merit_hydro contains its own dem that is distinct from merit-dem.

**Comment by jsta** [comment]
That makes it kind of confusing, so we're using merit_hydro(dem) not merit_dem. Should we rename the download script to `get_merit_hydro_dem.py`?

**Comment by jsta** [comment]
Also I think this means we can remove L140 in scripts/get_merit_dem.py - https://github.com/jonschwenk/rabpro/blob/main/Data/scripts/get_merit_dem.py#L140

**Comment by tzussman** [comment]
I think the script can probably be removed now that the functionality has been refactored into a module and provided a front-end through the CLI

**Comment by jonschwenk** [comment]
> Should we rename the download script to `get_merit_hydro_dem.py`?

I guess so, yeah. If we keep it. If not, we should make sure the CLI script is accurate.

**Comment by jsta** [comment]
@tzussman Do you have documentation examples for the CLI?
