### ISSUE TITLE
Mismatched coords and da in test and test reference

### ISSUE THREAD

**Issue by jsta** [jonschwenk/rabpro#44]
I can't get tests/test.py to pass. One thing I see is that the coords and da are mismatched between the code used to generate the reference file (`tests/basic_no_subbasin_stats.py`) and the test file (`tests/test.py`). The former has:

```python
coords = (32.97287, -88.15829)
da = 18680
```

while the latter has:

```python
coords = (56.22659, -130.87974)
da = 1994
```

My investigation shows that the test object matches the info specified in test.py so the basic_no_subbasin_stats.py info should probably be changed to match.

**Comment by jsta** [comment]
> test output (from `test.py`)
![image](https://user-images.githubusercontent.com/7844578/128747356-81eda01b-a251-45c1-ade7-9cd0733a77d2.png)

> reference file (from `basic_no_subbasin_stats.py`)
![image](https://user-images.githubusercontent.com/7844578/128747389-974fffdb-4d99-4973-8ba1-d1e0801c9bfa.png)

Something strange is going on the the row,column ids. Also the reference file is missing elevation info.

**Comment by tzussman** [comment]
`basic_no_subbasin_stats.py` is unrelated to `test.py`. I'm not sure what's going on in the second photo re: elevation data, but it's irrelevant. I'll be pushing an update w more test cases and cleaning up the test directory tmrw.
