### ISSUE TITLE
Remove RG dependency

### ISSUE THREAD

**Issue by jonschwenk** [jonschwenk/rabpro#48]
Involves copying `rivgraph.im_utils.regionprops()` and `.crop_binary_coords()`. The OpenCV dependence _might_ be removable if https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.find_contours provides the exact functionality of OpenCV's findContours. However, this is a heavily-used operation so lots of testing would need to be done to ensure that it's a 1:1 swap. No need to remove OpenCV, just throwing that bit in.

**Comment by tzussman** [comment]
Making new issue for OpenCB dependency
