### ISSUE TITLE
Add argument to get_datapaths to force rebuilding of VRTs

### ISSUE THREAD

**Issue by jsta** [jonschwenk/rabpro#57]

**Comment by jonschwenk** [comment]
Perhaps add a keyword argument to rebuild VRTS that is True by default.

**Comment by jsta** [comment]
I feel like we can turn off the vrt rebuilding for all steps except for the initial `profiler` call.

**Comment by jsta** [comment]
Think I've caught all the rebuilding, not sure about elev_profile because I can't run it currently (#63)
