### ISSUE TITLE
cli downloading outside of the rabpro package

### ISSUE THREAD

**Issue by jsta** [jonschwenk/rabpro#62]
Inside the rabpro package I can download data with:

```
./rabpro/cli/rabpro download merit n30w090 <username> <password>
```

However, with rabpro installed in a different environment it seems like I should be able to run:
```
rabpro download merit n30e150 <username> <password>
```

However, I get an error:

> Command 'rabro' not found, did you mean:...

**Comment by jonschwenk** [comment]
I assume the second call you're not actually misspelling `rabpro`. This is @tzussman territory.

**Comment by jsta** [comment]
Gah! It was just the misspelling that did it. I swear I copy-pasted.

**Comment by tzussman** [comment]
This works if you run `pip install -e .`. Currently the published versions of RaBPro don't have the updated setup.py or CLI code, but once we repackage it'll work.
