### ISSUE TITLE
Functions for interacting with gee_datasets.json

### ISSUE THREAD

**Issue by jsta** [jonschwenk/rabpro#64]
Maybe you all are more adept at quick inspection of json objects but I could use some python functions to list available datasets ids/bands/(start/end)dates.

**Comment by jonschwenk** [comment]
I haven't looked at the internals, but at some point @tzussman wrote code that parses the file...so some version of some of those tools must already exist. If you have a need for it, go ahead. Otherwise, that file should mostly be hidden from users.

**Comment by jsta** [comment]
I feel like this is unnecessary now that I've navigated the catalog.
