### ISSUE TITLE
Don't date-filter image collection bands that are not time indexed

### ISSUE THREAD

**Issue by jsta** [jonschwenk/rabpro#66]
`subbasin_stats` is working fine for me using the example "image" `Dataset ("JRC/GSW1_3/GlobalSurfaceWater",
                "occurrence")`

However, "image_collection" entries like `Dataset("JRC/GSW1_3/MonthlyRecurrence", "monthly_recurrence")` give me either an empty file on my GDrive or an error:

>TypeError: cannot unpack non-iterable NoneType object

depending on if `test` is True.

**Comment by jonschwenk** [comment]
This one's all @tzussman .

**Comment by tzussman** [comment]
I'll take a look at all of these sometime over the next two weeks

**Comment by jsta** [comment]
The following works in the code editor:

```javascript
var rect = ee.Geometry.Rectangle(-85.913312, 39.426099, -85.88453, 39.46298);

var dataset = ee.ImageCollection('JRC/GSW1_3/MonthlyRecurrence');

var reduced = dataset.map(function(image){
  return image.reduceRegions({
    collection:rect, 
    reducer:ee.Reducer.count(), 
    scale: 30
  });
});

var table = reduced.flatten();

print(table.getInfo())

Export.table.toDrive(table)
```

**Comment by jsta** [comment]
Just recording my debugging scripts here. This python snippet works:

```python
ee.Initialize()

rect = ee.Geometry.Rectangle(-85.913312, 39.426099, -85.88453, 39.46298)
dataset = ee.ImageCollection("JRC/GSW1_3/MonthlyRecurrence").select(
    "monthly_recurrence"
)

def reduce_function(image):
    res = image.reduceRegions(collection=rect, reducer=ee.Reducer.count(), scale=30)
    return res

reduced = dataset.map(reduce_function)
table = reduced.flatten()
table.getInfo()
```

**Comment by jsta** [comment]
The problem seems to be with `filterDate`

**Comment by jonschwenk** [comment]
Good find. The problem is that the images in `"JRC/GSW1_3/MonthlyRecurrence"` don't correspond to dates, but rather just months (as they're averaged over all years). Not sure the best way to handle this--I would hope the JSON dataset dictionary has information to parse these types, but maybe not...

**Comment by jsta** [comment]
```json
{
        "id": "JRC/GSW1_3/MonthlyRecurrence",
        "name": "JRC Monthly Water Recurrence, v1.3",
        "start_date": "1984-03-16",
        "end_date": "2021-01-01",
        "type": "image_collection",
        "bands": {
            "monthly_recurrence": {
                "units": null,
                "resolution": 30.000000000000004
            },
            "has_observations": {
                "units": null,
                "resolution": 30.000000000000004
            }
        }
    },
```

**Comment by jonschwenk** [comment]
I thought the purpose of L122 was to filter the date range. I don't know that we'd want to turn it off in general, would we?

**Comment by jsta** [comment]
Right now it's taking the minimum date and maximum date from the metadata (not user input) so it's not really filtering.

**Comment by jonschwenk** [comment]
Oh, that seems strange. There could be a reason it exists, although I can't guess what that would be...

**Comment by jonschwenk** [comment]
Yeah, that sounds correct.

**Comment by jsta** [comment]
Seems like a solution is to somehow turn off the default filtering but allow user filtering.

**Comment by jonschwenk** [comment]
I thought that's what we had, but you found a case where the default
filtering fails on this imageCollection. So probably just check keywords
for user-requested date filtering and call filterDate if they're provided,
otherwise don't?

**Comment by jsta** [comment]
We had:

> If no user specified date filter, then "filter" (but not really filter) by the por.

I propose:

> If no user specified filter, then no filter (return entire por).

PR incoming

**Comment by jsta** [comment]
The issue with checking keywords is that they don't seem to be consistent. We'd need a keyword dictionary.
