### ISSUE TITLE
Add an example of a custom subbasin_stats reducer function to docs or tests

### ISSUE THREAD

**Issue by jsta** [jonschwenk/rabpro#71]
One use-case might be returning land cover category stats using a "grouped" reducer:
https://developers.google.com/earth-engine/guides/reducers_grouping

**Comment by jsta** [comment]
These custom reducers seem to only operate secondary to pulling the data from GEE. They seem to only be for post processing.

**Comment by jonschwenk** [comment]
Yes, categorical aggregations (and many other types) are not currently handled. That was on our to-do list but we didn't get there. In GEE parlance, no data is "pulled"--aggregation happens on their servers and only the result is sent back. (I might be misunderstanding what you mean, though.)

**Comment by jsta** [comment]
There's an initial pull (on the server), the the initial pull is flattened to a table. Any custom reducer_funcs are currently only applied to the flattened table (after stats like mean, etc are computed).

**Comment by jonschwenk** [comment]
Ah, that makes sense for time-varying aggregations I guess. I think that's
how we designed it initially. GEE does spatial aggregations, then the user
has to temporally aggregate as they want. At least that's what I remember
us discussing.
