### ISSUE TITLE
Return subbasin_stats files to GDrive without basin geometry information

### ISSUE THREAD

**Issue by jsta** [jonschwenk/rabpro#75]
This seems to be causing an error on large pulls:

> ee.ee_exception.EEException: Request payload size exceeds the limit: 10485760 bytes.

**Comment by jsta** [comment]
This error is likely because the _uploading_ of geometries is too big not the download.

**Comment by jonschwenk** [comment]
I've also used the `selectors `kwarg in the exporting function, like answer 2 here: https://gis.stackexchange.com/questions/303138/google-earth-engine-remove-geometry-fields-from-featurecollection-for-export-t
