### ISSUE TITLE
Profiler takes redundant 'quiet' option

### ISSUE THREAD

**Issue by jonschwenk** [jonschwenk/rabpro#89]
I notice that there is both a `verbose ` and a `quiet ` kwarg when instantiating the profiler. I think if `verbose ` is False, `quiet `should be False.

**Comment by jsta** [comment]
verbose controls printing of status messages, quiet allow vrt rebuilding without showing any printout.

**Comment by jonschwenk** [comment]
quiet takes the value of verbose now.

**Comment by jonschwenk** [comment]
Make that: quiet takes the value of ~verbose.
