### ISSUE TITLE
vrts being rebuilt too often

### ISSUE THREAD

**Issue by jonschwenk** [jonschwenk/rabpro#90]
Two problems: one is that there is no way to disable the rebuilding of VRTs upon instantiating the profiler. I added an optional argument to pass that does this.

Second problem is that when I run `delineate_basins()`, the VRTs get rebuilt again.

Not sure what's going on but we need to fix this.

**Comment by jonschwenk** [comment]
Culprit seems to be `if not os.path.isfile(datapaths[key]) or force_rebuild:` in` utils.py`. For some reason, the vrt is getting deleted, I think. The path given by `datapaths[key]` is correct, and when I evaluate that path outside of `utils.py` (and after the rebuild), I get `os.path.isfile(r'X:\Data\MERIT_Hydro\MERIT_FDR\MERIT_FDR.vrt')` is `True`.

**Comment by jsta** [comment]
I get vrt rebuilding when calling the profiler (the quiet arg suppresses the vrt rebuilding message. No rebuilding when calling delineate_basins.

**Comment by jsta** [comment]
I have the RABPRO_CONFIG env var set but not RABPRO_DATA

**Comment by jsta** [comment]
The only stray line I see that could be triggering the rebuilding is https://github.com/jonschwenk/rabpro/blob/main/rabpro/subbasins.py#L537. Maybe try adding the `rebuild_vrts = False` argument there?

**Comment by jonschwenk** [comment]
Ah, good find! I'll bet that's it.

**Comment by jonschwenk** [comment]
No, it's not it because I was printing the rebuild variable and it was False...it was the path conditional that was triggering the rebuild.

**Comment by jonschwenk** [comment]
I was wrong, it _was_ the rebuild_vrt flag. There were actually two calls to get_datapaths() without the flag. Both are fixed now.
